#!/usr/bin/env python
# -*- coding: utf-8 -*-

# CAVEAT UTILITOR
#
# This file was automatically generated by Grako.
#
#    https://pypi.python.org/pypi/grako/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.


from __future__ import print_function, division, absolute_import, unicode_literals
from grako.parsing import graken, Parser


__version__ = (2014, 9, 22, 4, 21, 14, 0)

__all__ = [
    'rst2Parser',
    'rst2Semantics',
    'main'
]


class rst2Parser(Parser):
    def __init__(self, whitespace=None, nameguard=True, **kwargs):
        super(rst2Parser, self).__init__(
            whitespace=whitespace,
            nameguard=nameguard,
            **kwargs
        )

    @graken()
    def _document_(self):

        def block0():
            self._block_()
        self._positive_closure(block0)

        self._check_eof()

    @graken()
    def _indent_(self):
        self._pattern(r'[ \t]+\S')

    @graken()
    def _blankline_(self):
        self._pattern(r'[ \t]*\n')

    @graken()
    def _block_(self):
        with self._choice():
            with self._option():
                with self._optional():
                    self._indent_()
                self._line_()
            with self._option():
                self._blankline_()
            self._error('no available options')

    @graken()
    def _line_(self):
        self._pattern(r'[^ \t].*\n')


class rst2Semantics(object):
    def document(self, ast):
        return ast

    def indent(self, ast):
        return ast

    def blankline(self, ast):
        return ast

    def block(self, ast):
        return ast

    def line(self, ast):
        return ast


def main(filename, startrule, trace=False, whitespace=None):
    import json
    with open(filename) as f:
        text = f.read()
    parser = rst2Parser(parseinfo=False)
    ast = parser.parse(
        text,
        startrule,
        filename=filename,
        trace=trace,
        whitespace=whitespace)
    print('AST:')
    print(ast)
    print()
    print('JSON:')
    print(json.dumps(ast, indent=2))
    print()

if __name__ == '__main__':
    import argparse
    import string
    import sys

    class ListRules(argparse.Action):
        def __call__(self, parser, namespace, values, option_string):
            print('Rules:')
            for r in rst2Parser.rule_list():
                print(r)
            print()
            sys.exit(0)

    parser = argparse.ArgumentParser(description="Simple parser for rst2.")
    parser.add_argument('-l', '--list', action=ListRules, nargs=0,
                        help="list all rules and exit")
    parser.add_argument('-t', '--trace', action='store_true',
                        help="output trace information")
    parser.add_argument('-w', '--whitespace', type=str, default=string.whitespace,
                        help="whitespace specification")
    parser.add_argument('file', metavar="FILE", help="the input file to parse")
    parser.add_argument('startrule', metavar="STARTRULE",
                        help="the start rule for parsing")
    args = parser.parse_args()

    main(
        args.file,
        args.startrule,
        trace=args.trace,
        whitespace=args.whitespace
    )
